### ISSUE TITLE
Byte conversion incorrect

### ISSUE THREAD

**Issue by jph** [halogenandtoast/alchemist#36]
Hi, please excuse me, but I'm having issues performing byte conversion.

Your README.md states:

```ruby
1.kb.to.b.to_f == 1024.0
```

This evaluates to false for me:

```ruby
irb(main):010:0> 1.kb.to.b.to_f
=> 999.9999999999999
```

**Comment by halogenandtoast** [comment]
You are correct, this got broken in the rewrite and I'll address it soon.
